# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='prop_name',
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
