# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-13 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propdesk', '0005_auto_20160812_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
    ]
